# Generated by Django 3.2.8 on 2021-10-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='detect/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
